language: scala
sudo: false
script:
- sbt '; ^^ 0.13.17-RC2 ; compile'
- git clean -fdx
- sbt '; ++2.10.7! ; ^^0.13.17-RC2 ; compile' # https://github.com/sbt/sbt/issues/3907#issuecomment-361838022
jdk:
- oraclejdk9
